/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vishal
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    DataBase db=new DataBase();
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leusename = new javax.swing.JLabel();
        enewpass = new javax.swing.JLabel();
        ecpass = new javax.swing.JLabel();
        teusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tnewpass = new javax.swing.JPasswordField();
        tcpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));
        setMinimumSize(new java.awt.Dimension(1066, 590));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        leusename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leusename.setForeground(new java.awt.Color(0, 0, 204));
        leusename.setText("Enter User Name:");
        jPanel1.add(leusename);
        leusename.setBounds(100, 60, 136, 28);

        enewpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enewpass.setForeground(new java.awt.Color(0, 51, 255));
        enewpass.setText("Enter New Password:");
        jPanel1.add(enewpass);
        enewpass.setBounds(100, 100, 136, 28);

        ecpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ecpass.setForeground(new java.awt.Color(0, 51, 255));
        ecpass.setText("Confirm Password:");
        jPanel1.add(ecpass);
        ecpass.setBounds(100, 140, 136, 28);

        teusername.setFont(new java.awt.Font("Tahoma", 0, 14));
        jPanel1.add(teusername);
        teusername.setBounds(270, 60, 213, 28);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 190, 144, 38);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 190, 144, 38);
        jPanel1.add(tnewpass);
        tnewpass.setBounds(270, 100, 213, 28);
        jPanel1.add(tcpass);
        tcpass.setBounds(270, 140, 213, 28);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 560, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(270, 220, 580, 280);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("New Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(270, 160, 240, 50);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 260, 0, 0);

        jLabel15.setPreferredSize(new java.awt.Dimension(1730, 730));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1100, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                        if(teusername.getText().equals(""))
			{
				JOptionPane.showMessageDialog(null, "Plese Fillup User Name Field" );
			}
			else if(tnewpass.getText().equals(""))
			{
				JOptionPane.showMessageDialog(null, "Plese Fillup Password Field" );
			}
                        else if(tcpass.getText().equals(""))
			{
				JOptionPane.showMessageDialog(null, "Plese Fillup Conform Password Field" );
			}
			else
			{
                            
                            try
				{
					
					
                                    String Str1="select * from login_form where UserName='"+teusername.getText()+"'";
                                    ResultSet rs = db.getdata(Str1);
                                    if(rs.next())
                                    {                                                   
                                        try
                                         {
                                            String p=tnewpass.getText();
                                            String pc=tcpass.getText();
                                            if(p.equals(pc))
                                            {
                                                String Str=evt.getActionCommand();
                                                String q="UPDATE login_form SET Password ='"+tnewpass.getText()+"' WHERE UserName='"+teusername.getText()+"'";
                                                db.Ins_Upa_Del(q);
                                                JOptionPane.showMessageDialog(null,"SucessFull Reset Password");
                                                new LoginForm().setVisible(true);
                                                dispose();

                                            }
                                            else
                                            {
                                                JOptionPane.showMessageDialog(null,"Please Enter Same password in Both fields!");
                                            }

                                         }
                                         catch(Exception ea)
                                         {
                                            System.out.println(ea.getMessage());
                                         }
                                    }
                                    else
                                    {
                                    	JOptionPane.showMessageDialog(null, "Plese ReEnter Valid Username" );
                                    }
					
				}
				catch(SQLException  ee)
				{
					
				}
			}
                            
                            
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new LoginForm().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ecpass;
    private javax.swing.JLabel enewpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel leusename;
    private javax.swing.JPasswordField tcpass;
    private javax.swing.JTextField teusername;
    private javax.swing.JPasswordField tnewpass;
    // End of variables declaration//GEN-END:variables
}
