

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vishal
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    DataBase db=new DataBase();
    public LoginForm() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tuser = new javax.swing.JTextField();
        tpass = new javax.swing.JPasswordField();
        lUser = new javax.swing.JLabel();
        lpass = new javax.swing.JLabel();
        bcancel = new javax.swing.JButton();
        blogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bnewuser = new javax.swing.JButton();
        bchangpass = new javax.swing.JButton();
        bchangpass1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Form");
        setMinimumSize(new java.awt.Dimension(1066, 590));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 0)));
        jPanel1.setLayout(null);
        jPanel1.add(tuser);
        tuser.setBounds(182, 55, 285, 28);
        jPanel1.add(tpass);
        tpass.setBounds(182, 101, 285, 28);

        lUser.setBackground(new java.awt.Color(0, 0, 204));
        lUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lUser.setForeground(new java.awt.Color(0, 0, 204));
        lUser.setText("User Name:");
        jPanel1.add(lUser);
        lUser.setBounds(80, 54, 98, 27);

        lpass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lpass.setForeground(new java.awt.Color(0, 0, 204));
        lpass.setText("Password:");
        jPanel1.add(lpass);
        lpass.setBounds(80, 101, 98, 27);

        bcancel.setText("Cancel");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        jPanel1.add(bcancel);
        bcancel.setBounds(306, 155, 161, 33);

        blogin.setText("Login");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jPanel1.add(blogin);
        blogin.setBounds(80, 155, 174, 33);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 500, 200);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(408, 197, 520, 220);

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login Form");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(410, 140, 155, 48);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 0)));
        jPanel4.setLayout(null);

        bnewuser.setText("Create New User");
        bnewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewuserActionPerformed(evt);
            }
        });
        jPanel4.add(bnewuser);
        bnewuser.setBounds(30, 20, 144, 35);

        bchangpass.setText("Forget Password");
        bchangpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bchangpassActionPerformed(evt);
            }
        });
        jPanel4.add(bchangpass);
        bchangpass.setBounds(350, 20, 142, 35);

        bchangpass1.setText("Change Password");
        bchangpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bchangpass1ActionPerformed(evt);
            }
        });
        jPanel4.add(bchangpass1);
        bchangpass1.setBounds(190, 20, 142, 35);
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 10, 500, 50);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(410, 420, 520, 70);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 220, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewuserActionPerformed
       NewUser nu=new NewUser();
       nu.setVisible(true);
       dispose();
    }//GEN-LAST:event_bnewuserActionPerformed
    public String data()
    {
        return tuser.getText();
    }
    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
            
        String Str=evt.getActionCommand();
				 
			if(tuser.getText().equals(""))
			{
				JOptionPane.showMessageDialog(null, "Plese Enter Valid UserName" );
                                
			}
			else if(tpass.getText().equals(""))
			{
				JOptionPane.showMessageDialog(null, "Plese Enter Valid Password" );
			}
			else
			{
				try
				{
				
					if(Str.equals("Login"))
					{
						String Str1="select UserName,Password from login_form where UserName='"+tuser.getText()+"'and Password='"+tpass.getText()+"'";
                                                ResultSet rs = db.getdata(Str1);
                                                				
                                                if(rs.next())
						{
                                                    String str="select UserId from login_form where UserName='"+tuser.getText()+"'";
                                                    ResultSet rs1 = db.getdata(str);
                                                    if(rs1.next())
                                                    {
                                                        new HomePage(rs1.getString("UserId")).setVisible(true);
                                                        dispose();
                                                    }
                                                }
						else
						{
							JOptionPane.showMessageDialog(null, "Plese ReEnter Valid Username And password" );
						}
					}
				}
				catch(SQLException  ee)
				{
					JOptionPane.showMessageDialog(null, "Plese Enter Valid Username And password" );
				}
                                catch(NullPointerException np)
                                {
                                }
                                
			}
    }//GEN-LAST:event_bloginActionPerformed

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bcancelActionPerformed

    private void bchangpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bchangpassActionPerformed
        // TODO add your handling code here:
        new ForgotPassword().setVisible(true);
        dispose();
    }//GEN-LAST:event_bchangpassActionPerformed

    private void bchangpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bchangpass1ActionPerformed
        // TODO add your handling code here:
         new ForgotPassword().setVisible(true);
         dispose();
    }//GEN-LAST:event_bchangpass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bchangpass;
    private javax.swing.JButton bchangpass1;
    private javax.swing.JButton blogin;
    private javax.swing.JButton bnewuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lpass;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
