


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vishal
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    DataBase db=new DataBase();
    public NewUser() {
        initComponents();
    }
    LoginForm lf=new LoginForm();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpass = new javax.swing.JPasswordField();
        tcpass = new javax.swing.JPasswordField();
        lUser = new javax.swing.JLabel();
        lpass = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        buserok = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        lcpass = new javax.swing.JLabel();
        tuid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create New User ");
        setMinimumSize(new java.awt.Dimension(130, 730));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 0)));
        jPanel1.setLayout(null);

        tpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tpassFocusLost(evt);
            }
        });
        jPanel1.add(tpass);
        tpass.setBounds(300, 110, 162, 28);
        jPanel1.add(tcpass);
        tcpass.setBounds(300, 150, 162, 28);

        lUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lUser.setForeground(new java.awt.Color(0, 0, 153));
        lUser.setText("User Name:");
        jPanel1.add(lUser);
        lUser.setBounds(130, 70, 98, 27);

        lpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lpass.setForeground(new java.awt.Color(0, 0, 153));
        lpass.setText("Password:");
        jPanel1.add(lpass);
        lpass.setBounds(130, 110, 98, 28);
        jPanel1.add(tuser);
        tuser.setBounds(300, 70, 162, 28);

        buserok.setText("Ok");
        buserok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buserokActionPerformed(evt);
            }
        });
        jPanel1.add(buserok);
        buserok.setBounds(140, 200, 126, 33);

        bcancel.setText("Cancel");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        jPanel1.add(bcancel);
        bcancel.setBounds(320, 200, 132, 33);

        lcpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lcpass.setForeground(new java.awt.Color(0, 0, 153));
        lcpass.setText("Canform Password:");
        jPanel1.add(lcpass);
        lcpass.setBounds(130, 150, 120, 27);

        tuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuidActionPerformed(evt);
            }
        });
        jPanel1.add(tuid);
        tuid.setBounds(300, 30, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("User Id:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 30, 70, 30);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 550, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(596, 260, 570, 270);

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("New User");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(600, 210, 160, 48);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 270, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buserokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buserokActionPerformed
        
                        if(tuser.getText().equals(""))
			{
				JOptionPane.showMessageDialog(null, "Plese Enter UserName" );
			}
			else if(tpass.getText().equals(""))
			{
				JOptionPane.showMessageDialog(null, "Plese Enter Password" );
			}
                        else if(tcpass.getText().equals(""))
			{
				JOptionPane.showMessageDialog(null, "Plese Enter Confirm Password" );
			}
			else
			{
                            
				try
				{
                                    String p=tpass.getText();
                                    String pc=tcpass.getText();
                                    Pattern pt1 = Pattern.compile("^[a-zA-Z0-9]{8,8}+$");
                                    Matcher mh1 = pt1.matcher(p);
                                    Matcher mh2 = pt1.matcher(pc);
                                    
                                    boolean matchFound1 = mh1.matches();
                                    boolean matchFound2 = mh2.matches();
                                    
                                if (!(matchFound1))
				{
                                    	JOptionPane.showMessageDialog(null,"Please Enter password 8 Digit");
					tpass.setText("");
				}
                                else if(!(matchFound2))
				{
                                        JOptionPane.showMessageDialog(null,"Please Enter confirm password 8 Digit");
					tcpass.setText("");
				}
                                else
                                {
                                    if(p.equals(pc))
                                        {
                                           try{
                                               String str1="select UserId from login_form where UserId='"+tuid.getText()+"'";
                                               ResultSet rs1 = db.getdata(str1);
                                                    if(rs1.next())
                                                    {
                                                        JOptionPane.showMessageDialog(null,"Userid is allReady exist!");
                                                        tuid.setText("");
                                                    }
                                                    else
                                                    {
                                                        String Str=evt.getActionCommand();
                                                        String str="insert into login_form(UserId,UserName,Password)values('"+tuid.getText()+"','"+tuser.getText()+"','"+tpass.getText()+"')";
                                                        db.Ins_Upa_Del(str);
                                                        //JOptionPane.showMessageDialog(null,"SucessFuly Create New User!");
                                            
                                                        lf.setVisible(true);
                                                        dispose();
                                                    }
                                                }
                                           catch(Exception e){}
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(null,"Please Enter Same password in Both Password fields!");
                                        }
                                }
				}
				catch(Exception ea)
				{
                                      JOptionPane.showMessageDialog(null,"Please Enter Other Id");
				}
			}
       
    }//GEN-LAST:event_buserokActionPerformed

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        //Home h=new Home();
        lf.setVisible(true);
        dispose();
    }//GEN-LAST:event_bcancelActionPerformed

    private void tpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpassFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tpassFocusLost

    private void tuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton buserok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel lcpass;
    private javax.swing.JLabel lpass;
    private javax.swing.JPasswordField tcpass;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuid;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
