/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;



public class SearchForm_1 extends javax.swing.JFrame {
java.util.Date date1;
java.sql.Date sqldate1;
java.util.Date date2;
java.sql.Date sqldate2;
    /**
     * Creates new form SearchForm
     */
    DataBase db=new DataBase();
    private String user2;
    public SearchForm_1() {
        initComponents();
        groupButton();
        groupButton1();
    }
     SearchForm_1(String text) {
        this();
        user2=text;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tsearch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ir = new javax.swing.JRadioButton();
        er = new javax.swing.JRadioButton();
        ar = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        sr = new javax.swing.JRadioButton();
        amr = new javax.swing.JRadioButton();
        npr = new javax.swing.JRadioButton();
        dr = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isearch = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Form");
        setMinimumSize(new java.awt.Dimension(1308, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 51, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(80, 100, 198, 73);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 51, 0)));
        jPanel3.setLayout(null);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(50, 290, 156, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("From Date:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(20, 240, 106, 28);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton7.setText("Cancle");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(230, 290, 152, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("Enter You Want To Search:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(14, 198, 171, 30);

        tsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsearchMouseClicked(evt);
            }
        });
        jPanel3.add(tsearch);
        tsearch.setBounds(200, 200, 270, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        ir.setText("Income");
        ir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irActionPerformed(evt);
            }
        });

        er.setText("Expence");
        er.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erActionPerformed(evt);
            }
        });

        ar.setText("All");
        ar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ir)
                .addGap(18, 18, 18)
                .addComponent(er)
                .addGap(18, 18, 18)
                .addComponent(ar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ir)
                .addComponent(er)
                .addComponent(ar))
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(20, 20, 264, 54);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search On", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        sr.setText("Source");
        sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srActionPerformed(evt);
            }
        });

        amr.setText("Amount");
        amr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amrActionPerformed(evt);
            }
        });

        npr.setText("No Perticular");
        npr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nprActionPerformed(evt);
            }
        });

        dr.setText("Discription");
        dr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sr)
                    .addComponent(dr))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(npr)
                    .addComponent(amr))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr)
                    .addComponent(amr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dr)
                    .addComponent(npr))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(20, 80, 264, 108);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Result", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        isearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "T_Date", "Source", "Discription", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(isearch);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(486, 15, 640, 327);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 10, 1120, 330);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(80, 170, 1140, 350);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 1310, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        HomePage hp=new HomePage();
        hp.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SearchOn();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nprActionPerformed
        // TODO add your handling code here:
        tsearch.setVisible(false);
        jLabel18.setVisible(false);
    }//GEN-LAST:event_nprActionPerformed

    private void srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srActionPerformed
        // TODO add your handling code here:
        tsearch.setVisible(true);
        jLabel18.setVisible(true);
        tsearch.setHorizontalAlignment(tsearch.LEFT);
    }//GEN-LAST:event_srActionPerformed

    private void drActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drActionPerformed
        // TODO add your handling code here:
        tsearch.setVisible(true);
        jLabel18.setVisible(true);
        tsearch.setHorizontalAlignment(tsearch.LEFT);
    }//GEN-LAST:event_drActionPerformed

    private void amrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amrActionPerformed
        // TODO add your handling code here:
        tsearch.setVisible(true);
        jLabel18.setVisible(true);
        tsearch.setHorizontalAlignment(tsearch.RIGHT);
    }//GEN-LAST:event_amrActionPerformed

    private void arActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arActionPerformed
        // TODO add your handling code here:
        sr.setEnabled(false);
        dr.setEnabled(false);
        amr.setEnabled(false);
        npr.setEnabled(false);
        tsearch.setVisible(false);
        jLabel18.setVisible(false);
    }//GEN-LAST:event_arActionPerformed

    private void erActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erActionPerformed
        // TODO add your handling code here:
        sr.setEnabled(true);
        dr.setEnabled(true);
        amr.setEnabled(true);
        npr.setEnabled(true);
        tsearch.setVisible(true);
        jLabel18.setVisible(true);
    }//GEN-LAST:event_erActionPerformed

    private void irActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irActionPerformed
        // TODO add your handling code here:
        sr.setEnabled(true);
        dr.setEnabled(true);
        amr.setEnabled(true);
        npr.setEnabled(true);
        tsearch.setVisible(true);
        jLabel18.setVisible(true);
    }//GEN-LAST:event_irActionPerformed

    private void tsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsearchMouseClicked
        // TODO add your handling code here:
        tsearch.setText("");
        
    }//GEN-LAST:event_tsearchMouseClicked

    private void groupButton()
    {
        ButtonGroup bg1=new ButtonGroup();
        
        bg1.add(ir);
        bg1.add(er);
        bg1.add(ar);
    }
    private void groupButton1()
    {
        ButtonGroup bg2=new ButtonGroup();
        
        bg2.add(sr);
        bg2.add(dr);
        bg2.add(amr);
        bg2.add(npr);
    }
    private void SearchOn()
    {
        String st=null;
            date1=idate1.getDate();
            date2=idate2.getDate();
            sqldate1=new java.sql.Date(date1.getTime());
            sqldate2=new java.sql.Date(date2.getTime());
            
      if(ir.isSelected())
      {
        if(sr.isSelected())
        {
           st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' and Type='Income' AND Source='"+tsearch.getText()+"' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"')";
        }
      
        else if(dr.isSelected())
        {
            st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' and Type='Income' AND Discription='"+tsearch.getText()+"' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"')";
        }
        else if(amr.isSelected())
        {
            st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' and Type='Income' AND Amount='"+tsearch.getText()+"' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"')";
        }
        else if(npr.isSelected())
        {
            st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' and Type='Income' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"')";
        }
        else{  JOptionPane.showMessageDialog(null,"Please Select any Search on option"); }
      }            
     else if(er.isSelected())
      {
        if(sr.isSelected())
        {
           st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' and Type='Expense' AND Source='"+tsearch.getText()+"' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"')";
        }
      
        else if(dr.isSelected())
        {
            st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' and Type='Expense' AND Discription='"+tsearch.getText()+"' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"')";
        }
        else if(amr.isSelected())
        {
            st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' and Type='Expense' AND Amount='"+tsearch.getText()+"' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"')";
        }
        else if(npr.isSelected())
        {
            st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' and Type='Expense' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"')";
        }
        else{  JOptionPane.showMessageDialog(null,"Please Select any Search on option"); }
      }
     else if(ar.isSelected())
     {
         st="select T_Date,Source,Discription,Amount from in_out_table where UserId='"+user2+"' AND (T_Date Between '"+sqldate1+"' AND '"+sqldate2+"') ";
     }
     else{  JOptionPane.showMessageDialog(null,"Please Select any Search type option"); }
        ResultSet rs=db.getdata(st);
        isearch.setModel(DbUtils.resultSetToTableModel(rs));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             SearchForm sf=new SearchForm();
             sf.setVisible(true);
             sf.setResizable(false);
            }
        });
        
        
        
    }
      
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton amr;
    private javax.swing.JRadioButton ar;
    private javax.swing.JRadioButton dr;
    private javax.swing.JRadioButton er;
    private javax.swing.JRadioButton ir;
    private javax.swing.JTable isearch;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton npr;
    private javax.swing.JRadioButton sr;
    private javax.swing.JTextField tsearch;
    // End of variables declaration//GEN-END:variables
}

